version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist_php
    volumes:
      - .:/var/www/backend
    networks:
      - todolist

  nginx:
    image: nginx:alpine
    container_name: todolist_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/backend
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - todolist

  database:
    image: mysql:8.0
    container_name: todolist_db
    environment:
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: josemarlopdev
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todolist

networks:
  todolist:
    driver: bridge

volumes:
  db_data:
